import type { Metadata } from "next";
import { Lora, Geist_Mono } from "next/font/google";
// Font exploration: try swapping Geist with public sans-serif options such as 'Work_Sans', 'Sora', or 'Space_Grotesk'
// by replacing the import above. Keep variants lightweight for readability.
import "./globals.css";
import Header from "../components/Header";
import Footer from "../components/Footer";

const geistSans = Lora({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
